version: "3"
set:
  - "pipefail"
env:
  IMAGE_NAME: monorepo-demo
  CONTAINER_NAME: monorepo-demo
  TAG: latest
  CONTAINER_PORT: 3000
  HOST_PORT: 3000
tasks:
  remove-container:
    aliases: [rmc]
    description: "Remove container if it's running"
    labels: "Removing container"
    cmds:
      - docker container rm -f ${CONTAINER_NAME}
  build:
    description: "Build image"
    labels: "Building image"
    cmds:
      - docker image build -t ${IMAGE_NAME} -f Dockerfile .
  run:
    description: "Run container"
    labels: "Running container"
    cmds:
      - docker container run --name ${CONTAINER_NAME} -p ${HOST_PORT}:${CONTAINER_PORT} -d ${IMAGE_NAME}:${TAG}
  docker:
    interval: 20ms
    description: "Run docker commands"
    cmds:
      - task: remove-container
      - task: build
      - task: run

    sources:
      - "./Dockerfile"
      - "./services/**/*"
      - "./packages/**/*"
    preconditions:
      - test -e "Dockerfile"
