#!/usr/bin/env sh
# shellcheck disable=SC1091
. "$(dirname -- "$0")/_/husky.sh"

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
	echo "Your commit message is invalid. Aborting commit." >&2
	exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,120}$"; then
	echo "Your commit message is too long. Aborting commit." >&2
	exit 1
fi